// Generated by CoffeeScript 1.3.3
(function() {
  var DataOnWire,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DataOnWire = (function() {

    DataOnWire.validOrigins = ["http://0.0.0.0:9294", "http://www.galaxyzoo.org.s3-website-us-east-1.amazonaws.com/", "http://www.galaxyzoo.org/"];

    function DataOnWire() {
      this.sendMessage = __bind(this.sendMessage, this);

      this.receiveMessage = __bind(this.receiveMessage, this);
      window.addEventListener("message", this.receiveMessage, false);
    }

    DataOnWire.prototype.receiveMessage = function(e) {
      var band, bands, location, _i, _len, _results,
        _this = this;
      bands = e.data.bands;
      location = e.data.location;
      _results = [];
      for (_i = 0, _len = bands.length; _i < _len; _i++) {
        band = bands[_i];
        _results.push((function(band) {
          var url, xhr;
          url = "" + location + "_" + band + ".fits.fz";
          console.log(url);
          xhr = new XMLHttpRequest();
          xhr.open('GET', url);
          xhr.responseType = 'arraybuffer';
          xhr.onload = function() {
            var msg;
            msg = {
              origin: url,
              band: band,
              arraybuffer: xhr.response
            };
            return _this.sendMessage(msg);
          };
          return xhr.send();
        })(band));
      }
      return _results;
    };

    DataOnWire.prototype.sendMessage = function(msg) {
      var origin, _i, _len, _ref, _results;
      console.log('sendMessage');
      _ref = DataOnWire.validOrigins;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        origin = _ref[_i];
        console.log("Attempting to post message to " + origin);
        try {
          window.parent.postMessage(msg, origin);
          break;
        } catch (e) {
          console.log(e);
          continue;
        }
      }
      return _results;
    };

    return DataOnWire;

  })();

  this.DataOnWire = DataOnWire;

}).call(this);
