fs = require 'fs'
{spawn} = require 'child_process'
Hem = require 'hem'

buildHem = (uglify) ->
  hem = new Hem()
  source = hem.hemPackage().compile(uglify)
  fs.writeFileSync(__dirname + '/../public/navigator.js', source)

task 'build:navigator:debug', 'Build navigator module from interactive/ don\'t uglify', ->
  buildHem(false)

task 'build:navigator', 'Build navigator module from interactive/ uglify', ->
  buildHem(true)
