fs = require 'fs'
Hem = require 'hem'

buildHem = (uglify) ->
  hem = new Hem()
  source = hem.hemPackage().compile(uglify)
  fs.writeFileSync(__dirname + '/../public/fits.js', source)

task 'build:fits:debug', "Build fits viewer and don't uglify", ->
  buildHem(false)

task 'build:fits', 'Build fits viewer and uglify', ->
  buildHem(true)

